services:
  globo-systems:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NODE_PORT: 3000
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: globo_systems
    volumes: 
      - ./src:/app/src # Mount local source directory to container's /app/src
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: globo_systems
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data